### ISSUE TITLE
Error loading in 1.16.2 with Papi 2.10.9 (Using Paper 1.16.2 build 186)

### ISSUE THREAD

**Issue by RWoof** [SuperRonanCraft/Expansion-MySQL#2]
````
[PlaceholderAPI]: Task #159663 for PlaceholderAPI v2.10.9 generated an exception
Console 23:15:25
java.lang.NullPointerException: null
at me.SuperRonanCraft.expansionMySQL.Main.register(Main.java:36) ~[?:?]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:139) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_265]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_265]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_265]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
at java.util.stream.LongPipeline.reduce(LongPipeline.java:461) ~[?:1.8.0_265]
at java.util.stream.LongPipeline.sum(LongPipeline.java:419) ~[?:1.8.0_265]
at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:593) ~[?:1.8.0_265]
at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$2(LocalExpansionManager.java:288) ~[?:?]
at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-186]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-186]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-186]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
````

**Comment by SuperRonanCraft** [comment]
Thank you, I will be updating the expansion in a couple days, I will let you know when! Thank you.

**Comment by Permanently** [comment]
Any update on this by any chance?

**Comment by RWoof** [comment]
I'm running the dev build 122 of papi 2.10.10 on paper 1.16.5 build 468 and it seems to work normally for me!

**Comment by Permanently** [comment]
Just tried [PAPI 2.10.10 dev build 122](https://ci.extendedclip.com/job/PlaceholderAPI/122/); worked for me as well. Wonder if they added back some features that were defunct in 2.10.9?
