### ISSUE TITLE
Errors when loading

### ISSUE THREAD

**Issue by JamesHawkinss** [SuperRonanCraft/Expansion-MySQL#3]
Using latest version listed on papi ecloud - is there a more up-to-date version?

```26.10 17:25:05 [Server] WARN Task #381 for PlaceholderAPI v2.10.9 generated an exception
26.10 17:25:05 [Server] INFO java.lang.NullPointerException: null
26.10 17:25:05 [Server] INFO at me.SuperRonanCraft.expansionMySQL.Main.register(Main.java:36) ~[?:?]
26.10 17:25:05 [Server] INFO at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:139) ~[?:?]
26.10 17:25:05 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at java.util.stream.LongPipeline.reduce(LongPipeline.java:438) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at java.util.stream.LongPipeline.sum(LongPipeline.java:396) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526) ~[?:1.8.0_211]
26.10 17:25:05 [Server] INFO at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$2(LocalExpansionManager.java:288) ~[?:?]
26.10 17:25:05 [Server] INFO at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?]
26.10 17:25:05 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-246]
26.10 17:25:05 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-246]
26.10 17:25:05 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:948) ~[patched_1.16.3.jar:git-Paper-246]
26.10 17:25:05 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
26.10 17:25:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]```

**Comment by JamesHawkinss** [comment]
For those stuck, downgrade your PAPI to 2.10.6 - a breaking change was made in 2.10.7 and this dev doesn't seem to want to update his extension.
You can find the download for this PAPI version here: https://www.spigotmc.org/resources/placeholderapi.6245/download?version=328837

**Comment by SuperRonanCraft** [comment]
Ah, sorry for the late reply mate, honestly haven't checked my email for a while, I will try and get an update in the next couple of days, I saw that the API has changed a little and I need to update it. Thanks for letting me know!

**Comment by SuperRonanCraft** [comment]
actually seems like someone beat you to it, I will be posting more information here #2
