### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by chezzzer** [SuperRonanCraft/Expansion-MySQL#5]
Full error:
```
[21:24:40] [Server thread/WARN]: [PlaceholderAPI] Task #1116 for PlaceholderAPI v2.10.10-DEV-122 generated an exception
java.lang.NullPointerException: null
	at me.SuperRonanCraft.expansionMySQL.Main.register(Main.java:35) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:156) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:257) ~[?:?]
	at java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:605) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$1(LocalExpansionManager.java:307) ~[?:?]
	at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-708]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-708]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1077) ~[patched_1.16.5.jar:git-Paper-708]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-708]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

I have tried with multiple versions of placeholder API with no avail.

**Comment by ImMaxieZ** [comment]
Having the same issue. Let me know when there is an update.
